services:
  build:
    image: ${IMAGE_NAME_BUILD:-hbielenia/pypa-build}:1.2-py3.12-bullseye@sha256:b9e7eb4d96ba6dfd2d7538c11a89e9d7d7870e4be35e4386a4e9ac380640c4e2
    volumes:
      - ./:/usr/src/app
    command: python -m build
  build_exe:
    image: ${IMAGE_NAME_BUILD_EXE:-hbielenia/cx-freeze}:7.2-py3.12-windowsservercore-1809@sha256:23dd6de022d5addd57158ecd27537625b3dd78fded9bea47c64f1b6c1eb9e3fa
    volumes:
      - ./:c:\Users\ContainerUser\SourceCode
    command: cxfreeze build_exe
  test:
    build: ./test
    image: transactions2pln-test:latest
    volumes:
      - ./src:/usr/src/app:ro
    command: python -m unittest discover -q -b /usr/src/app
  test_dev:
    build: ./test
    image: transactions2pln-test:latest
    volumes:
      - ./src:/usr/src/app:ro
    command: python -W default -m unittest discover -b /usr/src/app
  typecheck:
    image: ${IMAGE_NAME_TYPECHECK:-hbielenia/mypy}:1.11-py3.12-bullseye@sha256:4381690982101274130aebbd538ab47775b8b13d0e0d53224b27ba2ac8043d40
    volumes:
      - ./src:/usr/src/app:ro
    command: mypy --strict --package transactions2pln
  lint:
    image: pipelinecomponents/flake8:0.16.0@sha256:6674fe93841130f36cd49542f5e62a3be7dd031d3fbb8858ecb8b389a9ac6c66
    volumes:
      - ./:/app:ro
    command: flake8
