services:
  build:
    image: ${IMAGE_NAME_BUILD:-hbielenia/pypa-build}:1.2-py3.11-bullseye@sha256:8c9e04ccfee55d9a4eb25a6cbc072454e46d60acccb35988ce225b64c34e6f1c
    volumes:
      - ./:/usr/src/app
    command: python -m build
  build_exe:
    image: ${IMAGE_NAME_BUILD_EXE:-hbielenia/cx-freeze}:7.2-py3.11-windowsservercore-1809@sha256:5fa91568ab940be2b3ccd5ac7bcf1a46e87647f4a3340d6ae59eb9b784b35b16
    volumes:
      - ./:c:\Users\ContainerUser\SourceCode
    command: cxfreeze build_exe
  test:
    build: ./test
    image: transactions2pln-test:latest
    volumes:
      - ./src:/usr/src/app:ro
    command: python -m unittest discover -q -b /usr/src/app
  typecheck:
    image: ${IMAGE_NAME_TYPECHECK:-hbielenia/mypy}:1.11-py3.11-bullseye@sha256:896db9543179759d8a2feb98bee7f1eec639d2385536868cab68ae307f39a161
    volumes:
      - ./src:/usr/src/app:ro
    command: mypy --strict --package transactions2pln
  lint:
    image: pipelinecomponents/flake8:0.16.0@sha256:6674fe93841130f36cd49542f5e62a3be7dd031d3fbb8858ecb8b389a9ac6c66
    volumes:
      - ./:/app:ro
    command: flake8
