version: '3'

tasks:
  build:
    cmds:
      - docker compose run --rm -u {{.USER_ID}} -e SOURCE_DATE_EPOCH={{.COMMIT_TIMESTAMP}} build
    vars:
      COMMIT_TIMESTAMP:
        sh: git cat-file commit HEAD | awk 'NR==3 {print $(NF-1)}'
      USER_ID:
        sh: id -u
  build_exe:
    cmds:
      - docker compose run --rm build_exe
  help:
    dir: ./src/
    cmds:
      - '{{ default "python3" .PYTHON }} -m transactions2pln --help'
  run:
    dir: ./src/
    cmds:
      - '{{ default "python3" .PYTHON }} -m transactions2pln {{ .CLI_ARGS }}'
  test:
    cmds:
      - docker compose run --rm --build test
  test-dev:
    cmds:
      - docker compose run --rm --build test_dev
  typecheck:
    cmds:
      - docker compose run --rm typecheck
  lint:
    cmds:
      - docker compose run --rm lint
